In [ ]:
# https://api.themoviedb.org/3/movie/top_rated?api_key=084a1dc314df44c153a8ee7c45817106
# "https://api.themoviedb.org/3/movie/top_rated?api_key=084a1dc314df44c153a8ee7c45817106&language=en-US&page=1")

In [ ]:
import pandas as pd 
import requests

In [ ]:
request=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=084a1dc314df44c153a8ee7c45817106&language=en-US&page=1")

In [ ]:
df=pd.DataFrame(request.json()['results'])[['id','original_title','popularity','vote_count','genre_ids']]

In [ ]:
df.head()

In [ ]:
df=pd.DataFrame()

In [ ]:
for i in range(1, 453):
    request = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=084a1dc314df44c153a8ee7c45817106&language=en-US&page={i}")
    tdf = pd.DataFrame(request.json()['results'])[['id', 'original_title', 'popularity', 'vote_count', 'genre_ids']]
    df = pd.concat([df, tdf], ignore_index=True)  # Use pd.concat instead of append

In [ ]:
df

In [ ]:
df.to_csv('movies.csv')

In [ ]:
requestnew=requests.get('https://www.opendata.nhs.scot/api/3/action/datastore_search?resource_id=d0ad59a3-431d-4b56-86fc-a04a2247fbd0&language=en-US')

In [ ]:
requestnew

In [ ]:
newdf=pd.DataFrame(requestnew.json()['result']['records'])

In [ ]:
newdf.head()

In [ ]:
newdf.to_csv('covid data age group wise.csv')

In [1]:
import requests
import pandas as pd

In [2]:
df=pd.DataFrame()

In [3]:
request=requests.get("https://www.opendata.nhs.scot/api/3/action/datastore_search?offset=000&resource_id=23b3bbf7-7a37-4f86-974b-6360d6748e08")
tempdf=pd.DataFrame(request.json()['result']['records'])
tempdf

,_id,Quarter,HB,HBQF,HBT,CancerType,CancerTypeQF,NumberOfEligibleReferrals62DayStandard,NumberOfEligibleReferrals62DayStandardQF,NumberOfEligibleReferralsTreatedWithin62Days,NumberOfEligibleReferralsTreatedWithin62DaysQF
0,1,2012Q1,S08000015,,S08000015,Breast,,52,,52,
1,2,2012Q1,S08000015,,S08000015,Cervical,,2,,2,
2,3,2012Q1,S08000015,,S08000015,Colorectal,,31,,29,
3,4,2012Q1,S08000015,,S08000015,Head & Neck,,2,,2,
4,5,2012Q1,S08000015,,S08000015,Lung,,34,,33,
...,...,...,...,...,...,...,...,...,...,...,...
95,96,2012Q1,S08000022,,S08000022,Urological,,16,,15,
96,97,2012Q1,S08000022,,S08000024,Breast,,1,,1,
97,98,2012Q1,S08000022,,S08000024,Melanoma,,1,,1,
98,99,2012Q1,S08000022,,S08000031,Lung,,3,,3,
99,100,2012Q1,S08000022,,S08000031,Upper GI,,1,,1,

In [4]:
request=requests.get(f"https://www.opendata.nhs.scot/api/3/action/datastore_search?resource_id=23b3bbf7-7a37-4f86-974b-6360d6748e08")
df=pd.DataFrame(request.json()['result']['records'])

for i in range(1,178):
    request=requests.get(f"https://www.opendata.nhs.scot/api/3/action/datastore_search?offset={i*100}&resource_id=23b3bbf7-7a37-4f86-974b-6360d6748e08")
    tempdf=pd.DataFrame(request.json()['result']['records'])
    df=pd.concat([df,tempdf],ignore_index=True)

In [5]:
df.head()

,_id,Quarter,HB,HBQF,HBT,CancerType,CancerTypeQF,NumberOfEligibleReferrals62DayStandard,NumberOfEligibleReferrals62DayStandardQF,NumberOfEligibleReferralsTreatedWithin62Days,NumberOfEligibleReferralsTreatedWithin62DaysQF
0,1,2012Q1,S08000015,,S08000015,Breast,,52,,52,
1,2,2012Q1,S08000015,,S08000015,Cervical,,2,,2,
2,3,2012Q1,S08000015,,S08000015,Colorectal,,31,,29,
3,4,2012Q1,S08000015,,S08000015,Head & Neck,,2,,2,
4,5,2012Q1,S08000015,,S08000015,Lung,,34,,33,

In [6]:

df.to_csv('cancer.csv')